# Generated by Django 5.0.3 on 2024-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text='Base currency code', max_length=3)),
                ('target_currency', models.CharField(help_text='Target currency code', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from base to target currency', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
        ),
    ]
