# Generated by Django 5.0.3 on 2024-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyconversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to convert', max_digits=10)),
                ('from_currency', models.CharField(help_text='Currency code to convert from', max_length=3)),
                ('to_currency', models.CharField(help_text='Currency code to convert to', max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, help_text='Converted amount', max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=6, help_text='Conversion rate', max_digits=10)),
                ('conversion_date', models.DateTimeField(auto_now_add=True, help_text='Conversion date')),
            ],
        ),
    ]
