# Generated by Django 5.0.3 on 2024-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyconversion', '0002_currencyconversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='from_currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], help_text='Currency code to convert from', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='to_currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], help_text='Currency code to convert to', max_length=3),
        ),
    ]
